### PR TITLE
Add search functionality to ride index views

### PR DESCRIPTION
**Pull request by lequytra**

### CODE REVIEW

**Comment by AlexanderOtavka** [comment]
See #29

**Comment by AlexanderOtavka** [comment]
Also, I'd like to see some tests.  Add them in `/test/controllers/{driver,passenger}/rides_controller_test.rb`

**Comment by AlexanderOtavka** [comment]
@lequytra I fixed the errors.  It was just a problem with your fixtures creating relationships with locations they shouldn't, or locations that didn't exist.  If you have questions about this, we can chat tonight.

There are still some failing tests.  I didn't change them to make them stop failing, because I don't know if the problem is with the tests or with the code.  Please take a look at them.

**Comment by AlexanderOtavka** [comment]
I'm starting to think this is too complicated.  It's bulky in the UI and hard to use.  We should probably just have a single location dropdown and a date picker to filter.  The date picker should have the option to be left blank.

**Comment by yashdavisgupta** [comment]
Hi All,
It's Yash here, sticking his head where it doesn't belong. I've changed the layout of the search/filter to be like most other filtering on webpages. We can (read: probably should) make filtering on mobile be a modal, but this change illustrates my point. I think it will also work well for the cards system I'm cooking up. Feel free to delete the commit I push here if this isn't to your liking Tran, just thought this might alleviate concerns.

**Comment by AlexanderOtavka** [comment]
The filter UI is still a bit too much.  Also, I think the ransack gem is a bit overkill for what we need here.  I'm going to take a stab at this myself on a separate branch because I have a specific idea in mind I want to try out.

**Comment by AlexanderOtavka** [comment]
I'm going to merge the leaner search for now in #106.  I can see us expanding it in the future to be more detailed.

**Pull request closed without merging**
