### PR TITLE
Notify per ride

### LINKED ISSUE #22: Notifications don't work well if you aren't a driver or a passenger (20 🍌)
Notifications don't play well if you are not a member of a ride, and you only posted a message.  You won't be notified if someone responds.

### PR DESCRIPTION
**Pull request by AlexanderOtavka**
Resolves #22 

# Changes

- Notifications have been decoupled from being in the ride
  - You can receive notifications for a ride you are not in
  - You can turn off notifications for a ride you are in
- Posting a message in a ride automatically turns on notifications for that ride
- There is a new root notifications page where you can change the user-based preferences

# Manual Testing

Create an initial test user with your real Grinnell email so you will actually receive email notifications.

For both passenger and driver apps:
1. Play with user-level notifications
  1. Go to notification preferences from the rides page
  2. Turn on email notifications and text message notifications, you should receive an email and a text confirming
  3. Turn off text notifications to save money (email notifications are free)
2. Play with ride-level notifications
  1. Create a ride
    - You should be subscribed for notifications automatically
  2. In an incognito window, create a separate user with a fake email
  3. Post a message as the other user
    - This should automatically subscribe that user
    - You should receive an email about the message posted
  4. Join the ride as the other user, then leave
    - You should receive an email about them joining
    - And another about them leaving
  5. Unsubscribe yourself from that ride's notifications
  6. Send another message from the fake user
    - You should **not** receive an email
  7. Join and leave the ride again as the other user
    - You should receive no emails about this either
  8. Create a ride as the other user
  9. Post a message on the other user's ride
    - This should subscribe you to the ride
  10. Respond to that message as the other user
    - You should receive an email

### CODE REVIEW

**Comment by AlexanderOtavka** [comment]
@yashdavisgupta I just updated the testing instructions.  Could you go through them as a driver, I will go through them as a passenger.

**Comment by AlexanderOtavka** [comment]
Actually, hold off.  It looks like email notifications are super broken.

**Comment by yashdavisgupta** [comment]
But it looks like SMS is working well!

**Comment by yashdavisgupta** [comment]
Texts saying "You are now receiving notifications..." should probably not go through every time you modify your notification preferences. In addition, if you are only turning on notifications for a single ride, it might be useful to list what that ride is in a human readable way rather than saying "You are..."

Thoughts?

**Comment by AlexanderOtavka** [comment]
@yashdavisgupta yeah, that is a bug.  There is code that only sends the "You are now receiving notifications" message when the notification method is changed, but it wasn't working.

**Comment by AlexanderOtavka** [comment]
These changes should fix that issue.

**Comment by AlexanderOtavka** [comment]
Ready for testing!

**Comment by yashdavisgupta** [comment]
There is still what I consider to be an issue: When a user with text notifications enabled updates notification preferences to include email notification, a user gets a text message saying they are subscribed in addition to an email. This seems like the wrong behavior, only an email should be sent.

**Comment by yashdavisgupta** [comment]
Testing as a Driver user:
Play with user-level notifications
_Things seem to work as expected, with the exception of the comment above_
Go to notification preferences from the rides page
_Works_
Turn on email notifications and text message notifications, you should receive an email and a text confirming
_Works_
Turn off text notifications to save money (email notifications are free)
_Works, with the exception of the above comment_
Play with ride-level notifications
_Works, with the exception of the above comment_
Create a ride
- You should be subscribed for notifications automatically
_True._
In an incognito window, create a separate user with a fake email
Post a message as the other user
- This should automatically subscribe that user
_True_
- You should receive an email about the message posted
_True_
Join the ride as the other user, then leave
- You should receive an email about them joining
True
- And another about them leaving
True
Unsubscribe yourself from that ride's notifications
Send another message from the fake user
- You should not receive an email
_False, I still receive notifications._
Join and leave the ride again as the other user
- You should receive no emails about this either
_False, I still receive notifications._
Create a ride as the other user
Post a message on the other user's ride
- This should subscribe you to the ride
_Works as expected_
Respond to that message as the other user
- You should receive an email
__Works as expected__

**Comment by AlexanderOtavka** [comment]
> Join and leave the ride again as the other user
> You should receive no emails about this either
> *False, I still receive notifications.*
@yashdavisgupta I fixed the message notifications, but I wasn't able to reproduce this case.  Could you double check?

**Pull request merged**
